# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M:\RMGPP Side projects\qt\dataReportGen1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 841)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1081, 801))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border-color: rgb(170, 85, 255);\n"
"background-color: rgb(170, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.cover_tab = QtWidgets.QWidget()
        self.cover_tab.setObjectName("cover_tab")
        self.label = QtWidgets.QLabel(self.cover_tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 51))
        self.label.setObjectName("label")
        self.fact_code_input = QtWidgets.QLineEdit(self.cover_tab)
        self.fact_code_input.setGeometry(QtCore.QRect(150, 20, 141, 31))
        self.fact_code_input.setObjectName("fact_code_input")
        self.label_2 = QtWidgets.QLabel(self.cover_tab)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 121, 51))
        self.label_2.setObjectName("label_2")
        self.contact_type_input = QtWidgets.QLineEdit(self.cover_tab)
        self.contact_type_input.setGeometry(QtCore.QRect(150, 80, 391, 71))
        self.contact_type_input.setObjectName("contact_type_input")
        self.label_3 = QtWidgets.QLabel(self.cover_tab)
        self.label_3.setGeometry(QtCore.QRect(560, 70, 121, 51))
        self.label_3.setObjectName("label_3")
        self.contact_name_input = QtWidgets.QLineEdit(self.cover_tab)
        self.contact_name_input.setGeometry(QtCore.QRect(690, 80, 371, 81))
        self.contact_name_input.setObjectName("contact_name_input")
        self.label_4 = QtWidgets.QLabel(self.cover_tab)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 121, 51))
        self.label_4.setObjectName("label_4")
        self.designation_input = QtWidgets.QLineEdit(self.cover_tab)
        self.designation_input.setGeometry(QtCore.QRect(150, 180, 391, 71))
        self.designation_input.setObjectName("designation_input")
        self.label_5 = QtWidgets.QLabel(self.cover_tab)
        self.label_5.setGeometry(QtCore.QRect(550, 180, 141, 51))
        self.label_5.setObjectName("label_5")
        self.contact_number_input = QtWidgets.QLineEdit(self.cover_tab)
        self.contact_number_input.setGeometry(QtCore.QRect(690, 190, 371, 31))
        self.contact_number_input.setObjectName("contact_number_input")
        self.label_6 = QtWidgets.QLabel(self.cover_tab)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 61, 51))
        self.label_6.setObjectName("label_6")
        self.email_input = QtWidgets.QLineEdit(self.cover_tab)
        self.email_input.setGeometry(QtCore.QRect(150, 270, 391, 31))
        self.email_input.setObjectName("email_input")
        self.saveButton = QtWidgets.QPushButton(self.cover_tab)
        self.saveButton.setGeometry(QtCore.QRect(150, 340, 131, 41))
        self.saveButton.setObjectName("saveButton")
        self.doneButton = QtWidgets.QPushButton(self.cover_tab)
        self.doneButton.setGeometry(QtCore.QRect(410, 340, 131, 41))
        self.doneButton.setObjectName("doneButton")
        self.tableView = QtWidgets.QTableView(self.cover_tab)
        self.tableView.setGeometry(QtCore.QRect(30, 400, 1001, 321))
        self.tableView.setObjectName("tableView")
        self.label_34 = QtWidgets.QLabel(self.cover_tab)
        self.label_34.setGeometry(QtCore.QRect(550, 260, 61, 51))
        self.label_34.setObjectName("label_34")
        self.notes_cover_input = QtWidgets.QLineEdit(self.cover_tab)
        self.notes_cover_input.setGeometry(QtCore.QRect(610, 270, 451, 31))
        self.notes_cover_input.setObjectName("notes_cover_input")
        self.lineEdit = QtWidgets.QLineEdit(self.cover_tab)
        self.lineEdit.setGeometry(QtCore.QRect(670, 340, 113, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.cover_tab)
        self.pushButton.setGeometry(QtCore.QRect(840, 340, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.cover_tab, "")
        self.visit_log_tab = QtWidgets.QWidget()
        self.visit_log_tab.setObjectName("visit_log_tab")
        self.label_7 = QtWidgets.QLabel(self.visit_log_tab)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 121, 51))
        self.label_7.setObjectName("label_7")
        self.fact_code_label_output = QtWidgets.QLabel(self.visit_log_tab)
        self.fact_code_label_output.setGeometry(QtCore.QRect(170, 40, 171, 51))
        self.fact_code_label_output.setText("")
        self.fact_code_label_output.setObjectName("fact_code_label_output")
        self.label_8 = QtWidgets.QLabel(self.visit_log_tab)
        self.label_8.setGeometry(QtCore.QRect(340, 40, 121, 51))
        self.label_8.setObjectName("label_8")
        self.date_of_visit_calendarWidget = QtWidgets.QCalendarWidget(self.visit_log_tab)
        self.date_of_visit_calendarWidget.setGeometry(QtCore.QRect(700, 40, 331, 241))
        self.date_of_visit_calendarWidget.setObjectName("date_of_visit_calendarWidget")
        self.date_of_visit_label_output = QtWidgets.QLabel(self.visit_log_tab)
        self.date_of_visit_label_output.setGeometry(QtCore.QRect(460, 50, 171, 31))
        self.date_of_visit_label_output.setText("")
        self.date_of_visit_label_output.setObjectName("date_of_visit_label_output")
        self.label_9 = QtWidgets.QLabel(self.visit_log_tab)
        self.label_9.setGeometry(QtCore.QRect(40, 100, 121, 51))
        self.label_9.setObjectName("label_9")
        self.visit_type_visitlog_input = QtWidgets.QLineEdit(self.visit_log_tab)
        self.visit_type_visitlog_input.setGeometry(QtCore.QRect(150, 110, 291, 31))
        self.visit_type_visitlog_input.setObjectName("visit_type_visitlog_input")
        self.label_10 = QtWidgets.QLabel(self.visit_log_tab)
        self.label_10.setGeometry(QtCore.QRect(30, 180, 181, 51))
        self.label_10.setObjectName("label_10")
        self.no_reports_requested_input = QtWidgets.QLineEdit(self.visit_log_tab)
        self.no_reports_requested_input.setGeometry(QtCore.QRect(220, 190, 141, 31))
        self.no_reports_requested_input.setObjectName("no_reports_requested_input")
        self.label_11 = QtWidgets.QLabel(self.visit_log_tab)
        self.label_11.setGeometry(QtCore.QRect(30, 230, 171, 51))
        self.label_11.setObjectName("label_11")
        self.no_reports_collected_input = QtWidgets.QLineEdit(self.visit_log_tab)
        self.no_reports_collected_input.setGeometry(QtCore.QRect(220, 240, 141, 31))
        self.no_reports_collected_input.setObjectName("no_reports_collected_input")
        self.saveButton_2 = QtWidgets.QPushButton(self.visit_log_tab)
        self.saveButton_2.setGeometry(QtCore.QRect(90, 360, 111, 41))
        self.saveButton_2.setObjectName("saveButton_2")
        self.doneButton_2 = QtWidgets.QPushButton(self.visit_log_tab)
        self.doneButton_2.setGeometry(QtCore.QRect(340, 360, 101, 41))
        self.doneButton_2.setObjectName("doneButton_2")
        self.tableView_2 = QtWidgets.QTableView(self.visit_log_tab)
        self.tableView_2.setGeometry(QtCore.QRect(50, 420, 961, 291))
        self.tableView_2.setObjectName("tableView_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.visit_log_tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(700, 340, 113, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.visit_log_tab)
        self.pushButton_3.setGeometry(QtCore.QRect(860, 340, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_12 = QtWidgets.QLabel(self.visit_log_tab)
        self.label_12.setGeometry(QtCore.QRect(40, 290, 171, 51))
        self.label_12.setObjectName("label_12")
        self.no_reports_collected_input_2 = QtWidgets.QLineEdit(self.visit_log_tab)
        self.no_reports_collected_input_2.setGeometry(QtCore.QRect(220, 300, 141, 31))
        self.no_reports_collected_input_2.setObjectName("no_reports_collected_input_2")
        self.tabWidget.addTab(self.visit_log_tab, "")
        self.list_reports_sheet_tab = QtWidgets.QWidget()
        self.list_reports_sheet_tab.setObjectName("list_reports_sheet_tab")
        self.label_15 = QtWidgets.QLabel(self.list_reports_sheet_tab)
        self.label_15.setGeometry(QtCore.QRect(80, 50, 121, 51))
        self.label_15.setObjectName("label_15")
        self.report_name_input = QtWidgets.QLineEdit(self.list_reports_sheet_tab)
        self.report_name_input.setGeometry(QtCore.QRect(230, 60, 581, 41))
        self.report_name_input.setObjectName("report_name_input")
        self.label_16 = QtWidgets.QLabel(self.list_reports_sheet_tab)
        self.label_16.setGeometry(QtCore.QRect(80, 120, 121, 51))
        self.label_16.setObjectName("label_16")
        self.format_input = QtWidgets.QLineEdit(self.list_reports_sheet_tab)
        self.format_input.setGeometry(QtCore.QRect(230, 130, 241, 41))
        self.format_input.setObjectName("format_input")
        self.saveButton_3 = QtWidgets.QPushButton(self.list_reports_sheet_tab)
        self.saveButton_3.setGeometry(QtCore.QRect(230, 210, 131, 41))
        self.saveButton_3.setObjectName("saveButton_3")
        self.doneButton_3 = QtWidgets.QPushButton(self.list_reports_sheet_tab)
        self.doneButton_3.setGeometry(QtCore.QRect(440, 210, 131, 41))
        self.doneButton_3.setObjectName("doneButton_3")
        self.tableView_3 = QtWidgets.QTableView(self.list_reports_sheet_tab)
        self.tableView_3.setGeometry(QtCore.QRect(70, 280, 941, 361))
        self.tableView_3.setObjectName("tableView_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.list_reports_sheet_tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 130, 113, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.list_reports_sheet_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 130, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.list_reports_sheet_tab, "")
        self.received_sheet_tab = QtWidgets.QWidget()
        self.received_sheet_tab.setObjectName("received_sheet_tab")
        self.label_14 = QtWidgets.QLabel(self.received_sheet_tab)
        self.label_14.setGeometry(QtCore.QRect(40, 30, 111, 41))
        self.label_14.setObjectName("label_14")
        self.report_name_comboBox = QtWidgets.QComboBox(self.received_sheet_tab)
        self.report_name_comboBox.setGeometry(QtCore.QRect(180, 30, 181, 41))
        self.report_name_comboBox.setObjectName("report_name_comboBox")
        self.label_17 = QtWidgets.QLabel(self.received_sheet_tab)
        self.label_17.setGeometry(QtCore.QRect(400, 30, 111, 41))
        self.label_17.setObjectName("label_17")
        self.format_label_output = QtWidgets.QLabel(self.received_sheet_tab)
        self.format_label_output.setGeometry(QtCore.QRect(470, 30, 141, 41))
        self.format_label_output.setText("")
        self.format_label_output.setObjectName("format_label_output")
        self.label_18 = QtWidgets.QLabel(self.received_sheet_tab)
        self.label_18.setGeometry(QtCore.QRect(570, 30, 151, 41))
        self.label_18.setObjectName("label_18")
        self.timeline_input = QtWidgets.QLineEdit(self.received_sheet_tab)
        self.timeline_input.setGeometry(QtCore.QRect(730, 40, 251, 41))
        self.timeline_input.setObjectName("timeline_input")
        self.label_19 = QtWidgets.QLabel(self.received_sheet_tab)
        self.label_19.setGeometry(QtCore.QRect(30, 90, 111, 41))
        self.label_19.setObjectName("label_19")
        self.start_time_output = QtWidgets.QLabel(self.received_sheet_tab)
        self.start_time_output.setGeometry(QtCore.QRect(10, 130, 131, 31))
        self.start_time_output.setText("")
        self.start_time_output.setObjectName("start_time_output")
        self.start_time_calendarWidget = QtWidgets.QCalendarWidget(self.received_sheet_tab)
        self.start_time_calendarWidget.setGeometry(QtCore.QRect(150, 100, 311, 211))
        self.start_time_calendarWidget.setObjectName("start_time_calendarWidget")
        self.label_20 = QtWidgets.QLabel(self.received_sheet_tab)
        self.label_20.setGeometry(QtCore.QRect(550, 100, 111, 41))
        self.label_20.setObjectName("label_20")
        self.end_time_output = QtWidgets.QLabel(self.received_sheet_tab)
        self.end_time_output.setGeometry(QtCore.QRect(550, 140, 121, 31))
        self.end_time_output.setText("")
        self.end_time_output.setObjectName("end_time_output")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.received_sheet_tab)
        self.calendarWidget.setGeometry(QtCore.QRect(680, 100, 311, 211))
        self.calendarWidget.setObjectName("calendarWidget")
        self.tableView_4 = QtWidgets.QTableView(self.received_sheet_tab)
        self.tableView_4.setGeometry(QtCore.QRect(30, 490, 991, 261))
        self.tableView_4.setObjectName("tableView_4")
        self.saveButton_4 = QtWidgets.QPushButton(self.received_sheet_tab)
        self.saveButton_4.setGeometry(QtCore.QRect(150, 420, 121, 41))
        self.saveButton_4.setObjectName("saveButton_4")
        self.doneButton_4 = QtWidgets.QPushButton(self.received_sheet_tab)
        self.doneButton_4.setGeometry(QtCore.QRect(400, 420, 121, 41))
        self.doneButton_4.setObjectName("doneButton_4")
        self.label_35 = QtWidgets.QLabel(self.received_sheet_tab)
        self.label_35.setGeometry(QtCore.QRect(30, 330, 111, 41))
        self.label_35.setObjectName("label_35")
        self.notes_received_sheet_input = QtWidgets.QLineEdit(self.received_sheet_tab)
        self.notes_received_sheet_input.setGeometry(QtCore.QRect(150, 340, 841, 41))
        self.notes_received_sheet_input.setObjectName("notes_received_sheet_input")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.received_sheet_tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(660, 420, 113, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.received_sheet_tab)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 420, 121, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.received_sheet_tab, "")
        self.data_input_tab = QtWidgets.QWidget()
        self.data_input_tab.setObjectName("data_input_tab")
        self.label_21 = QtWidgets.QLabel(self.data_input_tab)
        self.label_21.setGeometry(QtCore.QRect(50, 30, 111, 41))
        self.label_21.setObjectName("label_21")
        self.report_name_comboBox_2 = QtWidgets.QComboBox(self.data_input_tab)
        self.report_name_comboBox_2.setGeometry(QtCore.QRect(170, 40, 201, 31))
        self.report_name_comboBox_2.setObjectName("report_name_comboBox_2")
        self.label_22 = QtWidgets.QLabel(self.data_input_tab)
        self.label_22.setGeometry(QtCore.QRect(410, 40, 101, 31))
        self.label_22.setObjectName("label_22")
        self.format_label_output_2 = QtWidgets.QLabel(self.data_input_tab)
        self.format_label_output_2.setGeometry(QtCore.QRect(490, 40, 141, 41))
        self.format_label_output_2.setText("")
        self.format_label_output_2.setObjectName("format_label_output_2")
        self.label_23 = QtWidgets.QLabel(self.data_input_tab)
        self.label_23.setGeometry(QtCore.QRect(650, 40, 101, 31))
        self.label_23.setObjectName("label_23")
        self.sub_sheet_input = QtWidgets.QLineEdit(self.data_input_tab)
        self.sub_sheet_input.setGeometry(QtCore.QRect(740, 40, 251, 31))
        self.sub_sheet_input.setObjectName("sub_sheet_input")
        self.label_24 = QtWidgets.QLabel(self.data_input_tab)
        self.label_24.setGeometry(QtCore.QRect(600, 100, 131, 31))
        self.label_24.setObjectName("label_24")
        self.fac_data_point_input = QtWidgets.QLineEdit(self.data_input_tab)
        self.fac_data_point_input.setGeometry(QtCore.QRect(740, 100, 251, 31))
        self.fac_data_point_input.setObjectName("fac_data_point_input")
        self.label_25 = QtWidgets.QLabel(self.data_input_tab)
        self.label_25.setGeometry(QtCore.QRect(40, 100, 131, 31))
        self.label_25.setObjectName("label_25")
        self.ipa_data_point_comboBox = QtWidgets.QComboBox(self.data_input_tab)
        self.ipa_data_point_comboBox.setGeometry(QtCore.QRect(170, 100, 201, 31))
        self.ipa_data_point_comboBox.setObjectName("ipa_data_point_comboBox")
        self.label_26 = QtWidgets.QLabel(self.data_input_tab)
        self.label_26.setGeometry(QtCore.QRect(40, 160, 131, 31))
        self.label_26.setObjectName("label_26")
        self.data_avial_comboBox = QtWidgets.QComboBox(self.data_input_tab)
        self.data_avial_comboBox.setGeometry(QtCore.QRect(180, 160, 201, 31))
        self.data_avial_comboBox.setObjectName("data_avial_comboBox")
        self.data_avial_comboBox.addItem("")
        self.data_avial_comboBox.addItem("")
        self.data_avial_comboBox.addItem("")
        self.label_27 = QtWidgets.QLabel(self.data_input_tab)
        self.label_27.setGeometry(QtCore.QRect(410, 160, 101, 31))
        self.label_27.setObjectName("label_27")
        self.notes_datainput_input = QtWidgets.QLineEdit(self.data_input_tab)
        self.notes_datainput_input.setGeometry(QtCore.QRect(490, 160, 531, 31))
        self.notes_datainput_input.setObjectName("notes_datainput_input")
        self.tableView_5 = QtWidgets.QTableView(self.data_input_tab)
        self.tableView_5.setGeometry(QtCore.QRect(40, 360, 991, 381))
        self.tableView_5.setObjectName("tableView_5")
        self.saveButton_5 = QtWidgets.QPushButton(self.data_input_tab)
        self.saveButton_5.setGeometry(QtCore.QRect(120, 230, 121, 41))
        self.saveButton_5.setObjectName("saveButton_5")
        self.doneButton_5 = QtWidgets.QPushButton(self.data_input_tab)
        self.doneButton_5.setGeometry(QtCore.QRect(380, 230, 121, 41))
        self.doneButton_5.setObjectName("doneButton_5")
        self.label_37 = QtWidgets.QLabel(self.data_input_tab)
        self.label_37.setGeometry(QtCore.QRect(40, 290, 461, 51))
        self.label_37.setObjectName("label_37")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.data_input_tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(660, 230, 113, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.data_input_tab)
        self.pushButton_5.setGeometry(QtCore.QRect(840, 230, 131, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.data_input_tab, "")
        self.request_sheet_tab = QtWidgets.QWidget()
        self.request_sheet_tab.setObjectName("request_sheet_tab")
        self.label_28 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_28.setGeometry(QtCore.QRect(40, 40, 101, 41))
        self.label_28.setObjectName("label_28")
        self.visit_type_requestsheet_input = QtWidgets.QLineEdit(self.request_sheet_tab)
        self.visit_type_requestsheet_input.setGeometry(QtCore.QRect(160, 40, 261, 41))
        self.visit_type_requestsheet_input.setObjectName("visit_type_requestsheet_input")
        self.label_29 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_29.setGeometry(QtCore.QRect(480, 40, 111, 41))
        self.label_29.setObjectName("label_29")
        self.report_name_comboBox_3 = QtWidgets.QComboBox(self.request_sheet_tab)
        self.report_name_comboBox_3.setGeometry(QtCore.QRect(610, 40, 261, 31))
        self.report_name_comboBox_3.setObjectName("report_name_comboBox_3")
        self.label_30 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_30.setGeometry(QtCore.QRect(30, 440, 81, 31))
        self.label_30.setObjectName("label_30")
        self.format_label_output_3 = QtWidgets.QLabel(self.request_sheet_tab)
        self.format_label_output_3.setGeometry(QtCore.QRect(160, 100, 141, 41))
        self.format_label_output_3.setText("")
        self.format_label_output_3.setObjectName("format_label_output_3")
        self.label_31 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_31.setGeometry(QtCore.QRect(480, 110, 131, 41))
        self.label_31.setObjectName("label_31")
        self.data_need_from_label = QtWidgets.QLabel(self.request_sheet_tab)
        self.data_need_from_label.setGeometry(QtCore.QRect(620, 110, 191, 41))
        self.data_need_from_label.setText("")
        self.data_need_from_label.setObjectName("data_need_from_label")
        self.label_32 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_32.setGeometry(QtCore.QRect(40, 170, 81, 31))
        self.label_32.setObjectName("label_32")
        self.untill_input = QtWidgets.QLineEdit(self.request_sheet_tab)
        self.untill_input.setGeometry(QtCore.QRect(150, 160, 261, 41))
        self.untill_input.setObjectName("untill_input")
        self.label_33 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_33.setGeometry(QtCore.QRect(480, 160, 81, 31))
        self.label_33.setObjectName("label_33")
        self.breadth_input = QtWidgets.QLineEdit(self.request_sheet_tab)
        self.breadth_input.setGeometry(QtCore.QRect(570, 160, 261, 41))
        self.breadth_input.setObjectName("breadth_input")
        self.saveButton_6 = QtWidgets.QPushButton(self.request_sheet_tab)
        self.saveButton_6.setGeometry(QtCore.QRect(210, 340, 121, 41))
        self.saveButton_6.setObjectName("saveButton_6")
        self.doneButton_6 = QtWidgets.QPushButton(self.request_sheet_tab)
        self.doneButton_6.setGeometry(QtCore.QRect(440, 340, 121, 41))
        self.doneButton_6.setObjectName("doneButton_6")
        self.tableView_6 = QtWidgets.QTableView(self.request_sheet_tab)
        self.tableView_6.setGeometry(QtCore.QRect(410, 420, 651, 331))
        self.tableView_6.setObjectName("tableView_6")
        self.label_36 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_36.setGeometry(QtCore.QRect(40, 250, 81, 31))
        self.label_36.setObjectName("label_36")
        self.notes_reques_sheet_input = QtWidgets.QLineEdit(self.request_sheet_tab)
        self.notes_reques_sheet_input.setGeometry(QtCore.QRect(150, 240, 851, 41))
        self.notes_reques_sheet_input.setObjectName("notes_reques_sheet_input")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.request_sheet_tab)
        self.calendarWidget_2.setGeometry(QtCore.QRect(30, 470, 312, 236))
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.label_38 = QtWidgets.QLabel(self.request_sheet_tab)
        self.label_38.setGeometry(QtCore.QRect(110, 440, 201, 21))
        self.label_38.setObjectName("label_38")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.request_sheet_tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(670, 340, 113, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.request_sheet_tab)
        self.pushButton_6.setGeometry(QtCore.QRect(840, 340, 121, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.request_sheet_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Report Generator"))
        self.label.setText(_translate("MainWindow", "Factory Code"))
        self.label_2.setText(_translate("MainWindow", "Contact Type"))
        self.label_3.setText(_translate("MainWindow", "Contact Name"))
        self.label_4.setText(_translate("MainWindow", "Designation"))
        self.label_5.setText(_translate("MainWindow", "Contact Number"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.doneButton.setText(_translate("MainWindow", "Done"))
        self.label_34.setText(_translate("MainWindow", "Notes"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cover_tab), _translate("MainWindow", "Cover"))
        self.label_7.setText(_translate("MainWindow", "Factory Code"))
        self.label_8.setText(_translate("MainWindow", "Date of Visit"))
        self.label_9.setText(_translate("MainWindow", "Visit Type"))
        self.label_10.setText(_translate("MainWindow", "# Reports Requested"))
        self.label_11.setText(_translate("MainWindow", "# Reports Collected"))
        self.saveButton_2.setText(_translate("MainWindow", "Save"))
        self.doneButton_2.setText(_translate("MainWindow", "Done"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.label_12.setText(_translate("MainWindow", "Project Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visit_log_tab), _translate("MainWindow", "Visit Log"))
        self.label_15.setText(_translate("MainWindow", "Report Name"))
        self.label_16.setText(_translate("MainWindow", "Format"))
        self.saveButton_3.setText(_translate("MainWindow", "Save"))
        self.doneButton_3.setText(_translate("MainWindow", "Done"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.list_reports_sheet_tab), _translate("MainWindow", "List Reports Sheet"))
        self.label_14.setText(_translate("MainWindow", "Report Name"))
        self.label_17.setText(_translate("MainWindow", "Format"))
        self.label_18.setText(_translate("MainWindow", "Timeline"))
        self.label_19.setText(_translate("MainWindow", "Start Time"))
        self.label_20.setText(_translate("MainWindow", "End Time"))
        self.saveButton_4.setText(_translate("MainWindow", "Save"))
        self.doneButton_4.setText(_translate("MainWindow", "Done"))
        self.label_35.setText(_translate("MainWindow", "Notes"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.received_sheet_tab), _translate("MainWindow", "Received Sheet"))
        self.label_21.setText(_translate("MainWindow", "Report Name"))
        self.label_22.setText(_translate("MainWindow", "Format"))
        self.label_23.setText(_translate("MainWindow", "Sub sheet"))
        self.label_24.setText(_translate("MainWindow", "Fac Data Point"))
        self.label_25.setText(_translate("MainWindow", "IPA Data Point"))
        self.label_26.setText(_translate("MainWindow", "Data Availability"))
        self.data_avial_comboBox.setItemText(0, _translate("MainWindow", "direct"))
        self.data_avial_comboBox.setItemText(1, _translate("MainWindow", "indirect"))
        self.data_avial_comboBox.setItemText(2, _translate("MainWindow", "not available"))
        self.label_27.setText(_translate("MainWindow", "Notes"))
        self.saveButton_5.setText(_translate("MainWindow", "Save"))
        self.doneButton_5.setText(_translate("MainWindow", "Done"))
        self.label_37.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_input_tab), _translate("MainWindow", "Data Input"))
        self.label_28.setText(_translate("MainWindow", "Visit Type"))
        self.label_29.setText(_translate("MainWindow", "Report Name"))
        self.label_30.setText(_translate("MainWindow", "Format"))
        self.label_31.setText(_translate("MainWindow", "Data need from"))
        self.label_32.setText(_translate("MainWindow", "Untill"))
        self.label_33.setText(_translate("MainWindow", "Breadth"))
        self.saveButton_6.setText(_translate("MainWindow", "Save"))
        self.doneButton_6.setText(_translate("MainWindow", "Done"))
        self.label_36.setText(_translate("MainWindow", "Notes"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.request_sheet_tab), _translate("MainWindow", "Request Sheet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

